DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS snacks;
DROP TABLE IF EXISTS walks;

CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE snacks (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  brand TEXT UNIQUE NOT NULL,
  Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  user_id INTEGER,
  FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE walks (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  location TEXT NOT NULL,
  Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  user_id INTEGER,
  FOREIGN KEY (user_id) REFERENCES users (id)
);